// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Reservation struct {
	ID        int64     `json:"id"`
	TableSize int32     `json:"table_size"`
	StartTime time.Time `json:"start_time"`
	Booked    bool      `json:"booked"`
	Duration  int32     `json:"duration"`
}
